language: ruby
cache:
  - bundler
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: "G/BDhvs7f0kd+tVin4k9J4qDxDKzQBMkB+VsOKRQJI7wPJZe1AcJWAeGwaR99RXEdoaR4bXfE41rAerK+racwZTFrWaXPz10MgZqgvcfSvjhbI5UULdSEXZdSxvmfp/ip8lzV9iXO8xQKBv17m3ZH3mRQWlchAQ+nKAwJcM5g/phUt5O8g5Vc3tPEBXD5pVD/U9z/FZOcFkXNSpF3RKsGs1lsONwvpZNMYpveCXcZ62ta4dIZNvPnD68gdKdj9j3q+0v8Zf1FeVnaDLNzkfEnScXKp1tmIgmvo1CZhR97/XZNUtP1kWhSmzXKLVPiZiq4f+PIgPRR1bYkIcqZCasWpZiYdCPyfO7SuO1dpTpUx9RehiYIq+3EAnWCvCavwW69qnizy3Z3FOdjiCCdbagFAUczwyijxKcYqmvmCVsAvIckNUF9nFs0lOm9kTDOYp94M0yEnw4Jsw8H52kPM+O6wJxkSJF073oOOW6z43MU8Y8Dw1K19QLTGqhCypwzglE/YBvYTnpwrcJaZOWPq0K7PUcnWY7NKKk1WBDqVFKxMjQRf6dsEuD9mSkhsPNBPgBrjGyCc2STWZa0JxpxwxWGYpnEb2GHwwilC3K2tAHZQEOx34GHySRBJEMpjUI3FtAfcsl4e7MGjAp8LhyhYwqmkb4CERzfyDhMTTvO1sDDCs="
  app: rails-test-app-article
  on:
    repo: shubham9411/chat-app
